name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fececb341191df0170db1d3746292a61126e121a377eab04833158e4f1c2922"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"
