name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f1911c50c2abbfdba40f2857d841989bc6555afc2479322992ac0f609f97cd4"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"
