name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0cc45e76cb3e35f90ca8054e3505c764eb64170a03066a70d41d72ab71e5f4a"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"
