name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "197cc63bd48b94ef87bb53a846d7c9d0a1ac293fbd0b94bed6208800b3ffd03f"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"
