name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e02579910f4fc6a339715e9cafc3c3ff5b39ada4538bbb8bdcdca500331b823"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"
