name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fef40fcbcf4b1fb15551ddac083d68ba098529ac3b16154392ef7f66f84ae9dd"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"
