name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57512490ab681fb5e961d6983ad02d6b510c6a333be750a5616fb0b409b43cd1"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"
