name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.4.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1d81138f2d221cfb20981400148bc4f57376d7c42c179888f83ef024ffa9653"

[versions]
minecraft = "1.19.2"
quilt = "0.17.8"
