name = "WeeniePack 1.19.2"
author = "Karteufel"
version = "0.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e70b382d4a45c693497cb7a72afae38063ed415fd1667a3710f595520a54e41"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"
